// <auto-generated />
using System;
using ClimaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClimaAPI.Migrations
{
    [DbContext(typeof(ClimaAPIDBContext))]
    partial class ClimaAPIDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClimaAPI.Models.Clima", b =>
                {
                    b.Property<string>("codigo_icao")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("atualizado_em")
                        .HasColumnType("datetime2");

                    b.Property<string>("condicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condicao_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("direcao_vento")
                        .HasColumnType("int");

                    b.Property<int>("pressao_atmosferica")
                        .HasColumnType("int");

                    b.Property<int>("temp")
                        .HasColumnType("int");

                    b.Property<int>("umidade")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<int>("vento")
                        .HasColumnType("int");

                    b.Property<string>("visibilidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo_icao");

                    b.ToTable("Climas");
                });
#pragma warning restore 612, 618
        }
    }
}
